[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "label-flipping-project"
version = "1.5.2"
description = "Machine learning project for reseaching how to prevent an attack from Label Flipping Attack (LFA)"

authors = [
    { name = "MeoMuop3727" }
]

requires-python = ">=3.12,<3.13"

dependencies = [
    "jupyter==1.1.1",
    "matplotlib==3.9.0",
    "numpy==2.5.3",
    "pandas==3.12",
    "scikit-learn==1.9.1",
]

license = { file = "LICENSE" }

keywords = [
    "machine-learning",
    "label-flipping",
    "logistic-regression",
    "data-poisoning",
]

[project.urls]
Repository = "https://github.com/MeoMuop3727/label-flipping-project"